'use server'

import { createClient } from '@/lib/supabase/server'
import { createClient as createServiceClient } from '@supabase/supabase-js'
import { revalidatePath } from 'next/cache'
import { z } from 'zod'
import { currentTenant } from '@/lib/tenant'
import { requireVerified } from '@/lib/verification-gate'
import { reviewBulletinPost } from '@/lib/ai/review-bulletin-post'
import { generateCommunityTagline } from '@/lib/ai/generate-community-tagline'
import { extractReferralsFromReply } from '@/lib/ai/extract-referrals'
import { searchReferrals, type ReferralSearchResult } from '@/lib/ai/referral-search'
import { getEmbedding } from '@/lib/ai/embeddings'
import { sendEmail } from '@/lib/email/send'
import { siteUrl } from '@/lib/site-url'
import { VERIFICATION_TIER } from '@/lib/bulletin-constants'

function adminDb() {
  return createServiceClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
    { auth: { persistSession: false } }
  )
}

// ── Validation ────────────────────────────────────────────────

// Used by the review step: just the free-form description + location + date.
// Title and category are generated by AI, not entered by the user.
const ReviewInputSchema = z.object({
  detail: z.string().trim().min(10, 'Please describe your need in at least 10 characters'),
  geography_country: z.string().trim().min(1, 'Country is required'),
  geography_city: z.string().trim().optional().or(z.literal('')),
  required_by: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'Required by must be a date (YYYY-MM-DD)'),
})

// Used by the submit step: title comes from AI (editable by user), category derived from tags.
const PostSchema = z.object({
  title: z.string().trim().min(1, 'Title is required').max(120),
  detail: z.string().trim().max(2000).optional().or(z.literal('')),
  category: z.string().trim().default('General'),
  geography_country: z.string().trim().min(1, 'Country is required'),
  geography_city: z.string().trim().optional().or(z.literal('')),
  required_by: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'Required by must be a date (YYYY-MM-DD)'),
  tags: z.array(z.string()).max(20).optional(),
  board_type: z.enum(['business', 'community']).optional(),
})

const ReplySchema = z.object({
  post_id: z.string().uuid(),
  content: z.string().trim().min(1, 'Reply cannot be empty').max(2000),
})

// ── AI review step ─────────────────────────────────────────────

/**
 * Step 1 of the post wizard. Runs AI review on the draft post and
 * returns tags + feedback. Does NOT write to the DB — the member
 * sees the feedback and can either fix it or post anyway.
 *
 * Exported as a server action so the client form can call it on
 * the "Next →" click without page navigation.
 */
export async function reviewPost(input: unknown): Promise<{
  error: string | null
  suggested_title: string | null
  feedback: string | null
  tags: string[]
  is_complete: boolean
}> {
  const supabase = await createClient()
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const db = supabase as any
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: 'Not authenticated', suggested_title: null, feedback: null, tags: [], is_complete: true }

  const gate = await requireVerified(db, user.id)
  if (!gate.ok) return { error: gate.reason ?? 'Not allowed', suggested_title: null, feedback: null, tags: [], is_complete: true }

  const parsed = ReviewInputSchema.safeParse(input)
  if (!parsed.success) {
    return { error: parsed.error.issues[0].message, suggested_title: null, feedback: null, tags: [], is_complete: true }
  }

  const geo = [parsed.data.geography_city, parsed.data.geography_country].filter(Boolean).join(', ')
  const result = await reviewBulletinPost({
    detail: parsed.data.detail,
    geography: geo,
    required_by: parsed.data.required_by,
  })

  return { error: null, ...result }
}

// ── Submit (Step 2) ────────────────────────────────────────────

/**
 * Step 2: Member confirms the post (with or without addressing AI
 * feedback). Creates the bulletin_post row, then fires the matching
 * engine to notify up to 6 relevant businesses by email.
 *
 * Returns the post ID and matched businesses for the receipt screen.
 */
export async function submitBulletinPost(input: unknown): Promise<{
  error: string | null
  post_id?: string
  matched_businesses?: Array<{ id: string; name: string }>
  matched_members?: Array<{ id: string; name: string }>
  ai_referrals?: ReferralSearchResult[]
}> {
  const supabase = await createClient()
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const db = supabase as any
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: 'Not authenticated' }

  const gate = await requireVerified(db, user.id)
  if (!gate.ok) return { error: gate.reason ?? 'Not allowed' }

  const parsed = PostSchema.safeParse(input)
  if (!parsed.success) return { error: parsed.error.issues[0].message }

  // Refuse if required_by is in the past.
  const today = new Date().toISOString().split('T')[0]
  if (parsed.data.required_by < today) {
    return { error: 'Required by date cannot be in the past' }
  }

  // Fetch poster's name for email notifications.
  const { data: poster } = await db
    .from('profiles')
    .select('full_name, eo_membership_email')
    .eq('id', user.id)
    .maybeSingle() as { data: { full_name: string | null; eo_membership_email: string | null } | null }

  // Insert the post.
  const { data: post, error: postErr } = await db
    .from('bulletin_posts')
    .insert({
      member_id: user.id,
      board_type: parsed.data.board_type ?? 'business',
      title: parsed.data.title,
      detail: parsed.data.detail || null,
      category: parsed.data.category,
      tags: parsed.data.tags ?? [],
      geography_country: parsed.data.geography_country,
      geography_city: parsed.data.geography_city || null,
      required_by: parsed.data.required_by,
      status: 'open',
      ai_reviewed_at: new Date().toISOString(),
      tenant_id: currentTenant(),
    })
    .select('id')
    .maybeSingle() as { data: { id: string } | null; error: { message: string } | null }

  if (postErr || !post) return { error: postErr?.message ?? 'Failed to create post' }

  // ── Matching / notification engine ───────────────────────────
  // business board → match businesses by tag + geography
  // community board → notify verified members in the same country
  const boardType = (parsed.data.board_type ?? 'business') as 'business' | 'community'
  let matched: Array<{ id: string; name: string }> = []
  let matchedMembers: Array<{ id: string; name: string }> = []

  if (boardType === 'community') {
    // Generate AI tagline for community asks in the background — best-effort.
    void generateCommunityTagline({
      title: parsed.data.title,
      detail: parsed.data.detail ?? '',
      category: parsed.data.category,
    }).then(tagline => {
      if (tagline) {
        db.from('bulletin_posts').update({ ai_tagline: tagline }).eq('id', post.id)
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          .then(({ error }: { error: any }) => { if (error) console.error('[tagline] save failed:', error.message) })
      }
    }).catch(err => console.error('[tagline] generation failed:', err))

    matchedMembers = await notifyMembersGeo({
      postId: post.id,
      country: parsed.data.geography_country,
      city: parsed.data.geography_city ?? null,
      postTitle: parsed.data.title,
      posterName: poster?.full_name ?? 'A member',
      posterId: user.id,
      siteUrl: siteUrl(),
    })
    if (matchedMembers.length > 0) {
      await db
        .from('bulletin_posts')
        .update({ matched_business_ids: matchedMembers.map(m => m.id) })
        .eq('id', post.id)
    }
  } else {
    matched = await matchAndNotify({
      postId: post.id,
      tags: parsed.data.tags ?? [],
      detail: parsed.data.detail ?? '',
      country: parsed.data.geography_country,
      city: parsed.data.geography_city ?? null,
      postTitle: parsed.data.title,
      posterName: poster?.full_name ?? 'An EO member',
      siteUrl: siteUrl(),
    })
    if (matched.length > 0) {
      await db
        .from('bulletin_posts')
        .update({ matched_business_ids: matched.map(m => m.id) })
        .eq('id', post.id)
    }
  }

  // F18: surface top-3 relevant referrals from the referral DB.
  const queryText = [parsed.data.title, parsed.data.detail].filter(Boolean).join('\n')
  const aiReferrals = await searchReferrals(db, {
    queryText,
    boardType,
    matchCount: 3,
  })

  revalidatePath('/bulletin')
  revalidatePath('/community')
  return { error: null, post_id: post.id, matched_businesses: matched, matched_members: matchedMembers, ai_referrals: aiReferrals }
}

// ── Matching engine ────────────────────────────────────────────

// Extract meaningful lowercase words from tags or free text.
// Splits on hyphens, underscores, spaces; drops stopwords and tokens < 3 chars.
function extractKeywords(texts: string[]): Set<string> {
  const STOP = new Set(['a', 'an', 'the', 'and', 'or', 'for', 'in', 'of', 'to', 'with', 'by', 'at', 'on', 'is', 'are', 'be', 'as', 'we', 'our', 'your'])
  const words = new Set<string>()
  for (const text of texts) {
    text.toLowerCase()
      .replace(/[-_/]/g, ' ')
      .split(/\s+/)
      .forEach(w => {
        const clean = w.replace(/[^a-z0-9]/g, '')
        if (clean.length >= 3 && !STOP.has(clean)) words.add(clean)
      })
  }
  return words
}

// Score how well a business's tags match the need keywords.
// Uses prefix matching so "consult" matches "consulting", "consultant" etc.
function scoreTagMatch(bizTags: string[], needKeywords: Set<string>): number {
  if (!bizTags.length || !needKeywords.size) return 0
  const bizWords = extractKeywords(bizTags)
  let score = 0
  for (const needWord of needKeywords) {
    for (const bizWord of bizWords) {
      if (bizWord === needWord || bizWord.startsWith(needWord) || needWord.startsWith(bizWord)) {
        score++
        break
      }
    }
  }
  return score
}

async function matchAndNotify(input: {
  postId: string
  tags: string[]
  detail?: string
  country: string
  city: string | null
  postTitle: string
  posterName: string
  siteUrl: string
}): Promise<Array<{ id: string; name: string }>> {
  if (!process.env.SUPABASE_SERVICE_ROLE_KEY) return []
  const svc = adminDb()

  type BizRow = {
    id: string; name: string; owner_id: string; tags: string[];
    verification_tag: string | null; created_at: string; country: string | null;
    profiles: { eo_membership_email: string | null; full_name: string | null } | null
  }

  // Fetch all published non-slow-replier businesses in the same country.
  // We score them in JS so tag format differences (kebab, Title Case, etc.)
  // don't prevent a match.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { data: candidates } = await (svc as any)
    .from('businesses')
    .select('id, name, owner_id, tags, verification_tag, created_at, country, profiles!owner_id(eo_membership_email, full_name)')
    .eq('status', 'published')
    .eq('slow_replier', false)
    .not('owner_id', 'is', null)
    .ilike('country', input.country)
    .limit(200) as { data: BizRow[] | null }

  if (!candidates || candidates.length === 0) return []

  // Build keyword set from need tags + description for richer matching.
  const needKeywords = extractKeywords([...input.tags, input.detail ?? ''])

  // Score each business by word-level overlap with its tags.
  // Sort: score DESC → verification tier → recency. Keep top 6.
  const scored = candidates
    .map(biz => ({ biz, score: scoreTagMatch(biz.tags ?? [], needKeywords) }))
    .filter(({ score }) => score > 0)
    .sort((a, b) => {
      if (b.score !== a.score) return b.score - a.score
      const aTier = VERIFICATION_TIER[a.biz.verification_tag ?? 'unverified'] ?? 99
      const bTier = VERIFICATION_TIER[b.biz.verification_tag ?? 'unverified'] ?? 99
      if (aTier !== bTier) return aTier - bTier
      return new Date(b.biz.created_at).getTime() - new Date(a.biz.created_at).getTime()
    })

  const sorted = scored.slice(0, 6).map(({ biz }) => biz)

  if (sorted.length === 0) return []

  const postUrl = `${input.siteUrl}/bulletin/${input.postId}`

  // Fire match emails — best-effort, don't block on failure.
  for (const biz of sorted) {
    const email = biz.profiles?.eo_membership_email
    if (!email) continue
    sendEmail({
      to: email,
      subject: `New business need matches your listing: "${input.postTitle}"`,
      html: bulletinMatchEmailHtml({
        businessName: biz.name,
        ownerName: biz.profiles?.full_name ?? 'there',
        postTitle: input.postTitle,
        posterName: input.posterName,
        postUrl,
      }),
    }).catch(err => console.error('[bulletin-match] email failed for', biz.id, err))
  }

  return sorted.map(b => ({ id: b.id, name: b.name }))
}

function bulletinMatchEmailHtml(input: {
  businessName: string
  ownerName: string
  postTitle: string
  posterName: string
  postUrl: string
}) {
  const { businessName, ownerName, postTitle, posterName, postUrl } = input
  const esc = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#f9f6f0;">
  <div style="max-width:560px;margin:40px auto;background:white;border-radius:12px;padding:32px;box-shadow:0 2px 8px rgba(0,0,0,0.04);">
    <h1 style="font-size:18px;margin:0 0 12px;">Hi ${esc(ownerName)} — a member posted a need that matches ${esc(businessName)}</h1>
    <div style="background:#f4f1ec;border-left:4px solid #0A5C46;padding:12px 16px;margin:16px 0;border-radius:0 8px 8px 0;">
      <p style="margin:0;font-size:15px;font-weight:600;">${esc(postTitle)}</p>
      <p style="margin:4px 0 0;font-size:13px;color:#666;">Posted by ${esc(posterName)}</p>
    </div>
    <p style="font-size:14px;color:#444;line-height:1.5;">
      This member is looking for something your business may offer. View their full post and reply in the bulletin board.
    </p>
    <p style="margin-top:24px;">
      <a href="${postUrl}" style="background:#0A2218;color:white;padding:10px 20px;border-radius:8px;text-decoration:none;font-weight:600;">
        View the post &amp; reply
      </a>
    </p>
    <p style="font-size:12px;color:#999;margin-top:32px;border-top:1px solid #eee;padding-top:16px;">
      You received this because your Member Market listing matches this member's business need.
    </p>
  </div>
</body></html>`
}

// ── Replies ────────────────────────────────────────────────────

export async function replyToPost(input: unknown): Promise<{ error: string | null; id?: string }> {
  const supabase = await createClient()
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const db = supabase as any
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: 'Not authenticated' }

  const gate = await requireVerified(db, user.id)
  if (!gate.ok) return { error: gate.reason ?? 'Not allowed' }

  const parsed = ReplySchema.safeParse(input)
  if (!parsed.success) return { error: parsed.error.issues[0].message }

  // Refuse reply on a closed post. Fetch board_type for referral extraction.
  const { data: post } = await db
    .from('bulletin_posts')
    .select('id, status, member_id, board_type')
    .eq('id', parsed.data.post_id)
    .maybeSingle() as { data: { id: string; status: string; member_id: string; board_type: string } | null }
  if (!post) return { error: 'Post not found' }
  if (post.status !== 'open') return { error: 'This post is no longer accepting replies' }

  const { data: reply, error } = await db
    .from('post_responses')
    .insert({
      post_id: parsed.data.post_id,
      responder_member_id: user.id,
      content: parsed.data.content,
      tenant_id: currentTenant(),
    })
    .select('id')
    .maybeSingle() as { data: { id: string } | null; error: { message: string } | null }

  if (error) return { error: error.message }

  // F18: silently extract referrals from the reply in the background.
  // "No prompt, no opt-in." — per scope. Extraction is best-effort;
  // failure must never surface to the member or block the reply flow.
  if (reply?.id && process.env.SUPABASE_SERVICE_ROLE_KEY) {
    void runReferralExtraction({
      replyId: reply.id,
      postId: parsed.data.post_id,
      content: parsed.data.content,
      memberId: user.id,
      boardType: post.board_type as 'business' | 'community',
    })
  }

  const replyBasePath = post.board_type === 'community' ? '/community' : '/bulletin'
  revalidatePath(`${replyBasePath}/${parsed.data.post_id}`)
  return { error: null, id: reply?.id }
}

/**
 * Background referral extraction — runs after replyToPost returns.
 * Writes to referral_responses_business or _community via service-role.
 * All errors swallowed — the reply already succeeded.
 */
async function runReferralExtraction(input: {
  replyId: string
  postId: string
  content: string
  memberId: string
  boardType: 'business' | 'community'
}): Promise<void> {
  try {
    const referrals = await extractReferralsFromReply(input.content)
    if (referrals.length === 0) return

    const svc = adminDb()
    const table = input.boardType === 'community'
      ? 'referral_responses_community'
      : 'referral_responses_business'

    for (const r of referrals) {
      // Embed the referral text so similarity search can find it later.
      const embedText = [r.referred_name, r.referred_category, r.referred_location, r.full_text]
        .filter(Boolean).join(' ')
      const embedding = await getEmbedding(embedText)

      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const { error } = await (svc as any).from(table).insert({
        source_post_id: input.postId,
        source_response_id: input.replyId,
        referrer_member_id: input.memberId,
        referred_name: r.referred_name,
        referred_category: r.referred_category,
        referred_location: r.referred_location,
        full_text: r.full_text,
        embedding: embedding ?? null,
        relevance_score: 0,
        tenant_id: currentTenant(),
      })
      if (error) {
        console.error('[referral-extract] insert failed:', error.message, { referral: r.referred_name })
      }
    }
  } catch (err) {
    console.error('[referral-extract] background job failed:', err)
  }
}

// ── Post lifecycle ─────────────────────────────────────────────

export async function markFulfilled(postId: string): Promise<{ error: string | null }> {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: 'Not authenticated' }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const db = supabase as any
  const { data: post } = await db
    .from('bulletin_posts')
    .select('id, member_id, status, board_type')
    .eq('id', postId)
    .maybeSingle() as { data: { id: string; member_id: string; status: string; board_type: string } | null }
  if (!post) return { error: 'Post not found' }
  if (post.member_id !== user.id) return { error: 'Only the post author can mark it fulfilled' }
  if (post.status !== 'open') return { error: `Post is already ${post.status}` }

  const { error } = await db
    .from('bulletin_posts')
    .update({ status: 'fulfilled' })
    .eq('id', postId)
  if (error) return { error: error.message }

  const fulfillBasePath = post.board_type === 'community' ? '/community' : '/bulletin'
  revalidatePath(`${fulfillBasePath}/${postId}`)
  revalidatePath(fulfillBasePath)
  return { error: null }
}

/**
 * F18 satisfaction feedback: increment relevance_score on the referral the
 * member found most helpful. Called from the post-fulfilled dialog when
 * the poster picks "this past referral helped me."
 *
 * Higher relevance_score = surfaces earlier in future similarity searches.
 * The increment is small (+0.1) so a single vote doesn't dominate but
 * repeated helpfulness signals compound meaningfully.
 */
export async function updateReferralRelevance(
  referralId: string,
  boardType: 'business' | 'community'
): Promise<{ error: string | null }> {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: 'Not authenticated' }

  if (!process.env.SUPABASE_SERVICE_ROLE_KEY) return { error: 'Server not configured' }
  const svc = adminDb()
  const table = boardType === 'community'
    ? 'referral_responses_community'
    : 'referral_responses_business'

  // Fetch current score, increment by 0.1, update. Two queries is fine here —
  // this is a low-frequency event (marks-fulfilled happen rarely) and we
  // don't need atomic precision on a floating-point hint score.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { data: row } = await (svc as any)
    .from(table)
    .select('id, relevance_score')
    .eq('id', referralId)
    .maybeSingle() as { data: { id: string; relevance_score: number } | null }

  if (row) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    await (svc as any)
      .from(table)
      .update({ relevance_score: (row.relevance_score ?? 0) + 0.1 })
      .eq('id', referralId)
  }
  // Best-effort — relevance update failure must never block the UI.
  return { error: null }
}

// ── Community member notification engine ───────────────────────
// F05: finds verified members (not sponsors) in the same country
// and emails them about the community ask.

async function notifyMembersGeo(input: {
  postId: string
  country: string
  city: string | null
  postTitle: string
  posterName: string
  posterId: string
  siteUrl: string
}): Promise<Array<{ id: string; name: string }>> {
  if (!process.env.SUPABASE_SERVICE_ROLE_KEY) return []
  const svc = adminDb()

  type MemberRow = {
    id: string
    full_name: string
    eo_membership_email: string | null
    verification_tag: string | null
    country: string | null
  }

  // Verified non-sponsor members in the same country, excluding the poster.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { data: candidates } = await (svc as any)
    .from('profiles')
    .select('id, full_name, eo_membership_email, verification_tag, country')
    .eq('status', 'active')
    .eq('tenant_id', currentTenant())
    .ilike('country', input.country)
    .neq('id', input.posterId)
    .in('verification_tag', ['eo_member', 'eo_accelerator', 'eo_alumni', 'ypo_member', 'ypo_alumni'])
    .limit(50) as { data: MemberRow[] | null }

  if (!candidates || candidates.length === 0) return []

  // Sort by verification tier (highest first), cap at 6.
  const sorted = [...candidates].sort((a, b) => {
    const aTier = VERIFICATION_TIER[a.verification_tag ?? 'unverified'] ?? 99
    const bTier = VERIFICATION_TIER[b.verification_tag ?? 'unverified'] ?? 99
    return aTier - bTier
  }).slice(0, 6)

  const postUrl = `${input.siteUrl}/community/${input.postId}`

  for (const member of sorted) {
    const email = member.eo_membership_email
    if (!email) continue
    sendEmail({
      to: email,
      subject: `Community ask in ${input.country}: "${input.postTitle}"`,
      html: communityAskEmailHtml({
        recipientName: member.full_name,
        posterName: input.posterName,
        postTitle: input.postTitle,
        postUrl,
        country: input.country,
      }),
    }).catch(err => console.error('[community-match] email failed for', member.id, err))
  }

  return sorted.map(m => ({ id: m.id, name: m.full_name }))
}

function communityAskEmailHtml(input: {
  recipientName: string
  posterName: string
  postTitle: string
  postUrl: string
  country: string
}) {
  const { recipientName, posterName, postTitle, postUrl, country } = input
  const esc = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#f9f6f0;">
  <div style="max-width:560px;margin:40px auto;background:white;border-radius:12px;padding:32px;box-shadow:0 2px 8px rgba(0,0,0,0.04);">
    <h1 style="font-size:18px;margin:0 0 12px;">Hi ${esc(recipientName)} — a member in ${esc(country)} needs some help</h1>
    <div style="background:#f4f1ec;border-left:4px solid #0A5C46;padding:12px 16px;margin:16px 0;border-radius:0 8px 8px 0;">
      <p style="margin:0;font-size:15px;font-weight:600;">${esc(postTitle)}</p>
      <p style="margin:4px 0 0;font-size:13px;color:#666;">Posted by ${esc(posterName)}</p>
    </div>
    <p style="font-size:14px;color:#444;line-height:1.5;">
      This is a community ask from a fellow member in your area. If you have relevant experience, contacts, or can help in any way, head to the thread and reply.
    </p>
    <p style="margin-top:24px;">
      <a href="${postUrl}" style="background:#0A2218;color:white;padding:10px 20px;border-radius:8px;text-decoration:none;font-weight:600;">
        View the ask &amp; reply
      </a>
    </p>
    <p style="font-size:12px;color:#999;margin-top:32px;border-top:1px solid #eee;padding-top:16px;">
      You received this because you're a verified member in the same country as the poster.
    </p>
  </div>
</body></html>`
}

export async function extendPost(postId: string): Promise<{ error: string | null }> {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: 'Not authenticated' }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const db = supabase as any
  const { data: post } = await db
    .from('bulletin_posts')
    .select('id, member_id, status, required_by, board_type')
    .eq('id', postId)
    .maybeSingle() as { data: { id: string; member_id: string; status: string; required_by: string; board_type: string } | null }
  if (!post) return { error: 'Post not found' }
  if (post.member_id !== user.id) return { error: 'Only the post author can extend it' }
  if (post.status !== 'open') return { error: 'Only open posts can be extended' }

  // Extend by 14 days from current required_by.
  const current = new Date(post.required_by)
  current.setDate(current.getDate() + 14)
  const newDate = current.toISOString().split('T')[0]

  const { error } = await db
    .from('bulletin_posts')
    .update({ required_by: newDate, expiry_warned_at: null })
    .eq('id', postId)
  if (error) return { error: error.message }

  const extendBasePath = post.board_type === 'community' ? '/community' : '/bulletin'
  revalidatePath(`${extendBasePath}/${postId}`)
  return { error: null }
}

export interface MentionResult {
  id: string
  name: string
  handle: string
  type: 'member' | 'business'
  avatar_url: string | null
  subtitle: string | null
}

export async function searchMembersForMention(query: string): Promise<MentionResult[]> {
  if (!query || query.length < 1) return []
  if (/[,()*]/.test(query)) return []

  const supabase = await createClient()
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const db = supabase as any
  const safe = query.replace(/[%_\\]/g, m => '\\' + m)

  const [{ data: profiles }, { data: businesses }] = await Promise.all([
    db.from('profiles')
      .select('id, full_name, eo_chapter, avatar_url')
      .ilike('full_name', `%${safe}%`)
      .eq('status', 'active')
      .limit(5) as Promise<{ data: Array<{ id: string; full_name: string | null; eo_chapter: string | null; avatar_url: string | null }> | null }>,
    db.from('businesses')
      .select('id, name')
      .ilike('name', `%${safe}%`)
      .eq('status', 'published')
      .limit(4) as Promise<{ data: Array<{ id: string; name: string }> | null }>,
  ])

  const members: MentionResult[] = (profiles ?? [])
    .filter(p => p.full_name)
    .map(p => ({
      id: p.id,
      name: p.full_name!,
      handle: p.full_name!.replace(/\s+/g, '.'),
      type: 'member' as const,
      avatar_url: p.avatar_url,
      subtitle: p.eo_chapter,
    }))

  const bizs: MentionResult[] = (businesses ?? []).map(b => ({
    id: b.id,
    name: b.name,
    handle: b.name.replace(/\s+/g, '.'),
    type: 'business' as const,
    avatar_url: null,
    subtitle: 'Business',
  }))

  return [...members, ...bizs].slice(0, 8)
}
